services:
  db:
    image: postgres:18-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-root}
      POSTGRES_DB: ${DATABASE_NAME:-snippets}
    ports:
      - 5432:5432
    volumes:
      - snippets_db:/var/lib/postgresql/data

      # Esto inicializa la base de datos ejecutando el script `init.sql`.
      # Solo se ejecuta la primera vez que se hace `docker compose up` y el volumen está vacío.
      # https://hub.docker.com/_/postgres/#initialization-scripts
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: snippets_api
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PORT: ${API_PORT:-5000}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-root}
      DATABASE_USER: ${DATABASE_USER:-root}
      DATABASE_NAME: ${DATABASE_NAME:-snippets}
      TOKEN_SECRET: ${API_AUTH_SECRET}

  web:
    container_name: snippets_web
    image: nginx:1.29.4-alpine
    depends_on:
      - api
    ports:
      - 3000:80
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  snippets_db:
